export const STRINGS_FORM = {
  FORM_TITLE: 'hCard Builder',

  FORM_SUBTITLE_PERSONAL_DETAILS: 'PERSONAL DETAILS',
  FORM_LABEL_GIVEN_NAME: 'GIVEN NAME',
  FORM_LABEL_SURNAME: 'SURNAME',
  FORM_LABEL_EMAIL: 'EMAIL',
  FORM_LABEL_PHONE: 'PHONE',

  FORM_SUBTITLE_ADDRESS: 'ADDRESS',
  FORM_LABEL_HOUSE_NAME_OR_NUMBER: 'HOUSE NAME OR #',
  FORM_LABEL_STREET: 'STREET',
  FORM_LABEL_SUBURB: 'SUBURB',
  FORM_LABEL_STATE: 'STATE',
  FORM_LABEL_POSTCODE: 'POSTCODE',
  FORM_LABEL_COUNTRY: 'COUNTRY',

  FORM_BUTTON_UPLOAD_AVATAR: 'Upload Avatar',
  FORM_BUTTON_CREATE_HCARD: 'Create hCard'
};

export const STRINGS_PREVIEW = {
  PREVIEW_TITLE: 'HCARD PREVIEW',

  PREVIEW_LABEL_EMAIL: 'EMAIL',
  PREVIEW_LABEL_PHONE: 'PHONE',
  PREVIEW_LABEL_ADDRESS: 'ADDRESS',
  PREVIEW_LABEL_POSTCODE: 'POSTCODE',
  PREVIEW_LABEL_COUNTRY: 'COUNTRY'
};
